AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Architectures: ["x86_64"]
    Handler: bootstrap
    Runtime: provided.al2023
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        TABLE: !Ref Table
  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "*"
      AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      AllowHeaders:
        - Content-Type
        - Authorization
        - x-user-id
  Api:
    Cors:
      AllowOrigins:
        - http://localhost:3000
      AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      AllowHeaders:
        - Content-Type
        - Authorization

Parameters:
  ClientId:
    Type: String
    Default: ""
  ClientSecret:
    Type: String
    Default: ""
  IncludeWebSocket:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"

Conditions:
  IncludeWebSocketCondition: !Equals [!Ref IncludeWebSocket, "true"]

Resources:
  # WebSocket API
  ChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Condition: IncludeWebSocketCondition
    Properties:
      Name: ChatWebSocketAPI
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectIntegration

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectIntegration

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations

  SendMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: sendMessage
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendMessageIntegration

  SendMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Condition: IncludeWebSocketCondition
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketSendMessageFunction.Arn}/invocations

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Condition: IncludeWebSocketCondition
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - SendMessageRoute
    Properties:
      ApiId: !Ref ChatWebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Condition: IncludeWebSocketCondition
    Properties:
      StageName: dev
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref ChatWebSocketApi

  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Condition: IncludeWebSocketCondition
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/ws-connect/
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
              TableName: !Ref WebSocketConnectionsTable

  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Condition: IncludeWebSocketCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Condition: IncludeWebSocketCondition
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/ws-disconnect/
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
              TableName: !Ref WebSocketConnectionsTable

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Condition: IncludeWebSocketCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketSendMessageFunction:
    Type: AWS::Serverless::Function
    Condition: IncludeWebSocketCondition
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/ws-sendmessage/
      Timeout: 30
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
          MESSAGES_TABLE: !Ref MessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - Statement:
          - Effect: Allow
            Action:
              - 'execute-api:ManageConnections'
            Resource:
              - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ChatWebSocketApi}/*'

  WebSocketSendMessagePermission:
    Type: AWS::Lambda::Permission
    Condition: IncludeWebSocketCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketSendMessageFunction
      Principal: apigateway.amazonaws.com

  GetProductFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/get-product/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt Table.Arn

  PutProductFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/put-product/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: PUT
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn
  
  AuthUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/auth-user/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth/signup
            Method: POST
      Environment:
        Variables:
          AUTH_TABLE: !Ref AuthTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt AuthTable.Arn

  AuthLoginFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/auth-login/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth/login
            Method: POST
      Environment:
        Variables:
          AUTH_TABLE: !Ref AuthTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt AuthTable.Arn

  CreateRoomFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/create-room/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /user/rooms
            Method: POST

      Environment:
        Variables:
          ROOM_TABLE: !Ref RoomTable
          MEMBERS_TABLE: !Ref RoomMembersTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt RoomTable.Arn
                - !GetAtt RoomMembersTable.Arn
                - !Sub "${RoomMembersTable.Arn}/index/*"

  GetRoomFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/get-room/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /user/rooms/{room_id}
            Method: GET

      Environment:
        Variables:
          ROOM_TABLE: !Ref RoomTable
          MEMBERS_TABLE: !Ref RoomMembersTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt RoomTable.Arn
                - !GetAtt RoomMembersTable.Arn

  GetUserRoomsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/get-user-rooms/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /rooms/user
            Method: GET
        ApiUserRooms:
          Type: HttpApi
          Properties:
            Path: /user/rooms
            Method: GET
        OptionsEvent:
          Type: HttpApi
          Properties:
            Path: /rooms/user
            Method: OPTIONS
      Environment:
        Variables:
          ROOM_TABLE: !Ref RoomTable
          MEMBERS_TABLE: !Ref RoomMembersTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt RoomTable.Arn
                - !GetAtt RoomMembersTable.Arn
                - !Sub "${RoomMembersTable.Arn}/index/*"

  GetMessagesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: backend/functions/get-messages/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /rooms/{room_id}/messages
            Method: GET
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !GetAtt MessagesTable.Arn

  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: room_id
          AttributeType: S
      KeySchema:
        - AttributeName: room_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RoomMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: room_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: room_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserRoomsIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: room_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: room_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: room_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: connection_id
          AttributeType: S
        - AttributeName: room_id
          AttributeType: S
      KeySchema:
        - AttributeName: connection_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RoomConnectionsIndex
          KeySchema:
            - AttributeName: room_id
              KeyType: HASH
            - AttributeName: connection_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - x-user-id
        # AllowCredentials is omitted (treated as false)

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref AWS::StackName


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  
  WebSocketURL:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${ChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Condition: IncludeWebSocketCondition
